"""add_base_game_entry_id_to_game_in_collection

Revision ID: db0bdae8d334
Revises: 4c9235eeaa7c
Create Date: 2026-04-08 17:02:44.834399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db0bdae8d334'
down_revision: Union[str, Sequence[str], None] = '4c9235eeaa7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_in_collection', sa.Column('base_game_entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games_in_collection', 'games_in_collection', ['base_game_entry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games_in_collection', type_='foreignkey')
    op.drop_column('games_in_collection', 'base_game_entry_id')
    # ### end Alembic commands ###
